//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Screen { get; set; }
        public string OS { get; set; }
        public Nullable<int> FrontCamera { get; set; }
        public Nullable<int> RearCamera { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string MemoryCard { get; set; }
        public string SIMCard { get; set; }
        public string Connection { get; set; }
        public string Battery { get; set; }
        public string InternalStorage { get; set; }
        public Nullable<int> Weight { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
